# Claude Code Main Configuration
# Location: $XDG_CONFIG_HOME/claude-code/config.yaml

# Core settings
core:
  log_level: "info"
  telemetry: false
  update_check: weekly

# Default model settings
model:
  name: "claude-3-7-sonnet-20250219"
  context_window: 200000
  
# Performance tuning
performance:
  max_concurrent_requests: 4
  request_timeout: 120
  cache_enabled: true
  cache_ttl: 3600

# Output preferences
output:
  format: "markdown"
  color: true
  verbose: false

# Project behavior
project:
  ignore_patterns:
    - "node_modules"
    - ".git"
    - "dist"
    - "build"
  
# API Configuration - SENSITIVE DATA HANDLED SEPARATELY
api:
  url: "https://api.anthropic.com/v1"
  credentials_source: "script"
  credentials_script: "$XDG_CONFIG_HOME/claude-code/scripts/get_1password_key.sh"

# Editor integration
editors:
  warp:
    enabled: true
    ai_completions: true
    command_palette_integration: true
  cursor:
    enabled: true
    ai_suggestions: true
    inline_completions: true

# Command aliases - frequently used shortcuts
aliases:
  "e": "claude-code explain"
  "f": "claude-code fix"
  "i": "claude-code improve"
  "t": "claude-code test"
  "g": "claude-code generate"

# Basic rules for Claude Code behavior
rules:
  - name: "security_first"
    description: "Flag potential security vulnerabilities in code"
    enabled: true
    severity: "high"
  
  - name: "best_practices"
    description: "Follow industry best practices"
    enabled: true
    severity: "medium"
    
  - name: "performance_optimization"
    description: "Suggest performance improvements"
    enabled: true
    severity: "medium"
    
  - name: "test_coverage"
    description: "Ensure adequate test coverage"
    enabled: true
    severity: "medium"
    
  - name: "documentation"
    description: "Enforce proper documentation"
    enabled: true
    severity: "low"

# Integration hooks
hooks:
  pre_commit: true
  pre_push: false
  terminal_integration: true
