# Location: $XDG_CONFIG_HOME/claude-code/config.yaml

# Core settings
core:
  log_level: "info"
  telemetry: false
  update_check: weekly
  xdg_compliant: true
  default_languages: ["python", "terraform", "json", "go", "yaml", "javascript", "shell"]

# Default model settings
model:
  name: "claude-3-7-sonnet-20250219"
  context_window: 200000
  fallback_model: "claude-3-5-sonnet-20240620"

# API Configuration
api:
  url: "https://api.anthropic.com/v1"
  credentials_source: "script"
  credentials_script: "$XDG_CONFIG_HOME/claude-code/scripts/get_1password_key.sh"
  rate_limit_strategy: "adaptive"

# DevOps Integrations
integrations:
  github:
    enabled: true
    pr_review: true
    issue_analysis: true
    ci_optimization: true
  aws:
    enabled: true
    iac_validation: true
    credentials_source: "environment"
  kubernetes:
    enabled: true
    manifest_validation: true
    helm_chart_analysis: true
  terraform:
    enabled: true
    plan_analysis: true
    security_scan: true
  docker:
    enabled: true
    image_optimization: true
    colima_integration: true

# Command aliases - expanded
aliases:
  "e": "claude-code explain"
  "f": "claude-code fix"
  "i": "claude-code improve"
  "t": "claude-code test"
  "g": "claude-code generate"
  "r": "claude-code review"
  "s": "claude-code security-scan"
  "tf": "claude-code terraform-analyze"
  "k8s": "claude-code k8s-validate"
