core:
  log_level: "info"
  telemetry: false
  update_check: weekly
  xdg_compliant: true
  default_languages: ["python", "terraform", "json", "go", "yaml", "javascript", "shell"]
  multiline: true
  cleanup_period_days: 30
  include_coauthored_by: false
  verbose: false
  auto_updater: true

model:
  name: "claude-3-7-sonnet-20250219"
  context_window: 200000
  fallback_model: "claude-3-5-sonnet-20240620"

api:
  url: "https://api.anthropic.com/v1"
  credentials_source: "script"
  credentials_script: "$XDG_CONFIG_HOME/claude/scripts/get_1password_key.sh"
  rate_limit_strategy: "adaptive"
  timeout: 60000
  max_retries: 3

integrations:
  github:
    enabled: true
    pr_review: true
    issue_analysis: true
    ci_optimization: true
  aws:
    enabled: true
    iac_validation: true
    credentials_source: "environment"
  kubernetes:
    enabled: true
    manifest_validation: true
    helm_chart_analysis: true
  terraform:
    enabled: true
    plan_analysis: true
    security_scan: true
  docker:
    enabled: true
    image_optimization: true
    colima_integration: true

aliases:
  "e": "claude-code explain"
  "f": "claude-code fix"
  "i": "claude-code improve"
  "t": "claude-code test"
  "g": "claude-code generate"
  "r": "claude-code review"
  "s": "claude-code security-scan"
  "tf": "claude-code terraform-analyze"
  "k8s": "claude-code k8s-validate"

env:
  AWS_DEFAULT_REGION: "us-east-1"
  HOMEBREW_BUNDLE_FILE: "$XDG_CONFIG_HOME/brew/Brewfile"
  EDITOR: "nvim"

ui:
  theme: "dark"
  preferred_notif_channel: "terminal"
  show_progress: true
  confirm_destructive: true

permissions:
  allow_file_write: true
  allow_shell_commands: true
  allow_network_access: true
  deny_patterns: []

performance:
  max_concurrent_requests: 3
  memory_limit_mb: 2048
  cache_responses: true
